### ISSUE TITLE
update for ARIA standard product (S1-IFG v2.*)

### ISSUE THREAD

**Issue by pymonger** [aria-jpl/product_delivery#3]
* asjohnston [10:00 AM]
I did a quick draft of updating our ingest pipeline to process granules that have only a single data product.  Only having to deal with one file that's already compressed lets us throw away lots of code and significantly reduces our average ingest latency, so Ian and I will be very eager to get hdf5 products into production because it makes our lives so much easier.
I successfully ran this message through our draft workflow.  I paired a random .nc 2.x data product with the metadata/browse file from a random 1.x product, but things ended up in Earthdata Search UAT how you would expect:

https://search.uat.earthdata.nasa.gov/search/granules?p=C1217818727-ASF&pg[0][id]=S1-IFG_RM_M1S2_TN070_20181218T121737-20181124T121710_s3-resorb-8f68-v1.2.1-standard&g=G1225103529-ASF&m=0.0703125!0!2!1!0!0%2C2&tl=1529374504!4!!&q=grfn&ok=grfn

```
{
  "ProductName": "S1-IFG_RM_M1S2_TN070_20181218T121737-20181124T121710_s3-resorb-8f68-v1.2.1-standard",
  "DeliveryTime": "2018-12-19T01:36:56.502167",
  "Browse": {
    "Bucket": "hysds-imaging-fault-slip",
    "Key": "datasets/interferogram/v1.2.1/2018/11/24/S1-IFG_RM_M1S2_TN070_20181218T121737-20181124T121710_s3-resorb-8f68-v1.2.1-standard/filt_topophase.unw.geo.browse_small.png"
  },
  "Product": {
    "Bucket": "aria-ops-dataset-bucket",
    "Key": "datasets/interferogram/v2.0.0/2018/08/23/S1-D-R-032-tops-20180823_20180817-215317-09391S_07296S-PP-3d8d-v2_0_0/S1-D-R-032-tops-20180823_20180817-215317-09391S_07296S-PP-3d8d-v2_0_0.nc"
  },
  "Metadata": {
    "Bucket": "hysds-imaging-fault-slip",
    "Key": "datasets/interferogram/v1.2.1/2018/11/24/S1-IFG_RM_M1S2_TN070_20181218T121737-20181124T121710_s3-resorb-8f68-v1.2.1-standard/S1-IFG_RM_M1S2_TN070_20181218T121737-20181124T121710_s3-resorb-8f68-v1.2.1-standard_delivery.dataset.json"
  }
}
```

We'll need to revisit that message schema and make it more general when we work on CNM, but if you want to use this message as a reference for implementation we should be able to start ingesting products in hours or days after you're ready to deliver them.

**Comment by pymonger** [comment]
* asjohnston [9:22 AM]
And for completeness here's the schema we're using to validate the _delivery.dataset.json metdata file, no changes here:
```
{
 "type": "object",
 "required": [
  "label",
  "location",
  "metadata",
  "creation_timestamp"
 ],
 "properties": {
  "label": {
   "type": "string",
   "minLength": 1
  },
  "creation_timestamp": {
   "$ref": "#/definitions/iso_datetime"
  },
  "location": {
   "type": "object",
   "required": [
    "type",
    "coordinates"
   ],
   "properties": {
    "type": {
     "type": "string",
     "enum": ["Polygon"]
    },
    "coordinates": {
     "type": "array",
     "minItems": 1,
     "items": {
      "type": "array",
      "minItems": 4,
      "items": {
       "$ref": "#/definitions/coordinate"
      }
     }
    }
   }
  },
  "metadata": {
   "type": "object",
   "required": [
    "ogr_bbox",
    "master_scenes",
    "slave_scenes",
    "sensingStart",
    "sensingStop",
    "orbitNumber",
    "platform",
    "beamMode",
    "direction",
    "dataset_type",
    "product_type",
    "polarization",
    "lookDirection",
    "trackNumber",
    "perpendicularBaseline",
    "swath"
   ],
   "properties": {
    "ogr_bbox": {
     "type": "array",
     "minItems": 4,
     "maxItems": 4,
     "items": {
      "#ref": "#/definitions/coordinate"
     }
    },
    "master_scenes": {
     "$ref": "#/definitions/granule_list"
    },
    "slave_scenes": {
     "$ref": "#/definitions/granule_list"
    },
    "sensingStart": {
     "$ref": "#/definitions/datetime"
    },
    "sensingStop": {
     "$ref": "#/definitions/datetime"
    },
    "orbitNumber": {
     "type": "array",
     "minItems": 1,
     "items": {
      "type": "integer",
      "minimum": 1
     }
    },
    "platform": {
     "type": "array",
     "minItems": 1,
     "items": {
      "type": "string",
      "enum": ["Sentinel-1A", "Sentinel-1B"]
     }
    },
    "beamMode": {
     "type": "string",
     "enum": ["IW", "EW", "WV", "S1", "S2", "S3", "S4", "S5", "S6"]
    },
    "direction": {
     "type": "string",
     "enum": ["ascending", "descending"]
    },
    "dataset_type": {
     "type": "string"
    },
    "product_type": {
     "type": "string"
    },
    "polarization": {
     "type": "string",
     "enum": ["VV", "HH", "VV+VH", "HH+HV"]
    },
    "lookDirection": {
     "type": "string",
     "enum": ["right", "left"]
    },
    "trackNumber": {
     "type": "integer",
     "minimum": 1,
     "maximum": 175
    },
    "perpendicularBaseline": {
     "type": "number"
    },
    "swath": {
     "type": "array",
     "minItems": 1,
     "items": {
      "type": "integer",
      "enum": [1, 2, 3]
     }
    }
   }
  }
 },
 "definitions": {
  "granule_list": {
   "type": "array",
   "minItems": 1,
   "items": {
    "type": "string",
    "minLength": 1
   }
  },
  "coordinate": {
   "type": "array",
   "minItems": 2,
   "maxItems": 2,
   "items": [
    {
     "type": "number",
     "minimum": -180,
     "maximum": 180
    },
    {
     "type": "number",
     "minimum": -90,
     "maximum": 90
    }
   ]
  },
  "datetime": {
   "type": "string",
   "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(3[0-1]|[1-2][0-9]|0[1-9])T(2[0-3]|[0-1][0-9]):[0-5][0-9]:[0-5][0-9]$"
  },
  "iso_datetime": {
   "type": "string",
   "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(3[0-1]|[1-2][0-9]|0[1-9])T(2[0-3]|[0-1][0-9]):[0-5][0-9]:[0-5][0-9]\\.[0-9]{6}Z$"
  }
 }
}
```

* asjohnston [9:27 AM]
And no change to the response message, either.  This is just an example success message, we never wrote a full jsonschema for it:
```
{
  "Status": "success",
  "IngestTime": "2018-12-20T17:07:56.638725",
  "DeliveryTime": "2018-12-20T16:56:31.395587",
  "ProductName": "S1-IFG_RM_M1S2_TN005_20181220T004013-20181202T003845_s1-resorb-88c1-v1.2.1-standard"
 }
```

**Comment by asjohnston-asf** [comment]
I think the code changes to update the format of the publish message look like this: 
 https://github.com/hysds/product_delivery/compare/develop...asjohnston-asf:netcdf_delivery?expand=1

That assumes the browse image is still `filt_topophase.unw.geo.browse_small.png`, but you can update that however you need to based on how you're generating browse images going forward.

**Comment by asjohnston-asf** [comment]
Regarding metadata validation, the names of many metadata fields were tweaked between v1.2.1 and v2.0.0 (based on http://aria-ops-dataset-bucket.s3-us-west-2.amazonaws.com/datasets/interferogram/v2.0.0/2018/08/23/S1-D-R-032-tops-20180823_20180817-215317-09391S_07296S-PP-3d8d-v2_0_0/S1-D-R-032-tops-20180823_20180817-215317-09391S_07296S-PP-3d8d-v2_0_0.met.json).

ASF can plan on updating our validation logic for the new field names:

sensingStart -> sensing_start
sensingStop -> sensing_stop
orbitNumber -> orbit_number
beamMode -> beam_mode
direction -> orbit_direction
lookDirection -> look_direction
trackNumber -> track_number
perpendicularBaseline -> perpendicular_baseline

Our current validation also expects a "swath" field that's missing from the new metadata file.  I assume that's a result of v1.2.1 products being single-swath scenes and v2.x products being merged scenes, so we can drop swath on our end as well.

**Comment by asjohnston-asf** [comment]
And the timestamp format for `sensing_start` and `sensing_stop` changed as well, we'll accommodate that on the ASF end.

"2018-08-23T21:53:02" -> "2018-08-23T21:53:02.649645Z"

**Comment by asjohnston-asf** [comment]
FYI, updated jsonschema for the metadata file to address the camelCase, date format, and swath changes:

```
{
  "type": "object",
  "required": [
    "label",
    "location",
    "metadata",
    "creation_timestamp"
  ],
  "properties": {
    "label": {
      "type": "string",
      "minLength": 1
    },
    "creation_timestamp": {
      "$ref": "#/definitions/iso_datetime"
    },
    "location": {
      "type": "object",
      "required": [
        "type",
        "coordinates"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["Polygon"]
        },
        "coordinates": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "array",
            "minItems": 4,
            "items": {
              "$ref": "#/definitions/coordinate"
            }
          }
        }
      }
    },
    "metadata": {
      "type": "object",
      "required": [
        "ogr_bbox",
        "master_scenes",
        "slave_scenes",
        "sensing_start",
        "sensing_stop",
        "orbit_number",
        "platform",
        "beam_mode",
        "orbit_direction",
        "dataset_type",
        "product_type",
        "polarization",
        "look_direction",
        "track_number",
        "perpendicular_baseline"
      ],
      "properties": {
        "ogr_bbox": {
          "type": "array",
          "minItems": 4,
          "maxItems": 4,
          "items": {
            "#ref": "#/definitions/coordinate"
          }
        },
        "master_scenes": {
          "$ref": "#/definitions/granule_list"
        },
        "slave_scenes": {
          "$ref": "#/definitions/granule_list"
        },
        "sensing_start": {
          "$ref": "#/definitions/iso_datetime"
        },
        "sensing_stop": {
          "$ref": "#/definitions/iso_datetime"
        },
        "orbit_number": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "integer",
            "minimum": 1
          }
        },
        "platform": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": ["Sentinel-1A", "Sentinel-1B"]
          }
        },
        "beam_mode": {
          "type": "string",
          "enum": ["IW", "EW", "WV", "S1", "S2", "S3", "S4", "S5", "S6"]
        },
        "orbit_direction": {
          "type": "string",
          "enum": ["ascending", "descending"]
        },
        "dataset_type": {
          "type": "string"
        },
        "product_type": {
          "type": "string"
        },
        "polarization": {
          "type": "string",
          "enum": ["VV", "HH", "VV+VH", "HH+HV"]
        },
        "look_direction": {
          "type": "string",
          "enum": ["right", "left"]
        },
        "track_number": {
          "type": "integer",
          "minimum": 1,
          "maximum": 175
        },
        "perpendicular_baseline": {
          "type": "number"
        }
      }
    }
  },
  "definitions": {
    "granule_list": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "coordinate": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": [
        {
          "type": "number",
          "minimum": -180,
          "maximum": 180
        },
        {
          "type": "number",
          "minimum": -90,
          "maximum": 90
        }
      ]
    },
    "iso_datetime": {
      "type": "string",
      "pattern": "^[0-9]{4}-(0[1-9]|1[0-2])-(3[0-1]|[1-2][0-9]|0[1-9])T(2[0-3]|[0-1][0-9]):[0-5][0-9]:[0-5][0-9]\\.[0-9]{6}Z$"
    }
  }
}
```

**Comment by asjohnston-asf** [comment]
I pushed another commit to address the new naming convention for browse image files:

https://github.com/hysds/product_delivery/compare/master...asjohnston-asf:netcdf_delivery?expand=1

**Comment by pymonger** [comment]
@NamrataM:

For the browse image to send to ASF, send the `<datasetid>.interferogram_coarse.png` only, e.g. S1-A-R-035-tops-20150828_20150617-020822-41835N_39969N-PP-920f-v2_0_0.interferogram.browse_coarse.png.

**Comment by asjohnston-asf** [comment]
And the ASF SNS topic for our test pipeline for validating these changes is ` 
arn:aws:sns:us-east-1:406893895021:ingest-test-jobs`

**Comment by NamrataM** [comment]
Merged the code updates from @asjohnston-asf on Jan 22, 2019. Ran a test with a v2.0 IFG product and got the updated SNS message:
`{  
   "Product":{  
      "Bucket":"aria-ops-dataset-bucket",
      "Key":"datasets/interferogram/v2.0.0/2015/06/17/S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0/S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0.nc"
   },
   "DeliveryTime":"2019-01-23T23:37:23.435225",
   "Browse":{  
      "Bucket":"aria-ops-dataset-bucket",
      "Key":"datasets/interferogram/v2.0.0/2015/06/17/S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0/S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0.interferogram.browse_coarse.png"
   },
   "ProductName":"S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0",
   "ResponseTopic":{  
      "Region":"us-west-2",
      "Arn":"arn:aws:sns:us-west-2:136244619446:product-notification-test"
   },
   "Metadata":{  
      "Bucket":"aria-ops-dataset-bucket",
      "Key":"datasets/interferogram/v2.0.0/2015/06/17/S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0/S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0_delivery.dataset.json"
   }
}`

**Comment by NamrataM** [comment]
ASF validation on metadata passed and was able to receive acknowledgment from them. Here's the product on Earthdata Search UAT:  https://search.uat.earthdata.nasa.gov/search/granules?p=C1217818727-ASF&pg[0][id]=S1-A-R-035-tops-20150617_20150524-020819-41839N_39969N-PP-4931-v2_0_0&tl=1532475703!4!!&q=grfn&ok=grfn
